# true | false
enabled: true
comment: My distribution
export_name: distro
#default_root_object: index.html

# http1.1 | http2
http_version: http2
# ipv6: false

# custom_error_responses:
#   -
#     ErrorCachingMinTTL: 0
#     ErrorCode: 404
#     ResponseCode: 200
#     ResponsePagePath: /index.html

ssl:
  # acm | cloudfront | iam
  type: cloudfront
  # sni-only | vip
  support_method: sni-only
  # SSLv3 | TLSv1 | TLSv1_2016 | TLSv1.1_2016 | TLSv1.2_2018
  minimum_protocol_version: TLSv1.2_2018

behaviours:
  default:
    # GET, HEAD, OPTIONS, PUT, PATCH, POST, and DELETE
    AllowedMethods:
      - GET
      - HEAD
    Compress: true
    TargetOriginId: s3bucket
    ForwardedValues:
      Cookies:
        Forward: none
      QueryString: true
    # allow-all | redirect-to-https | https-only
    ViewerProtocolPolicy: redirect-to-https
  # nondefaultcachebehaviours:
  #   -
  #     AllowedMethods:
  #       - GET
  #       - HEAD
  #       - OPTIONS
  #     Compress: true
  #     TargetOriginId: s3bucket
  #     ForwardedValues:
  #       Cookies:
  #         Forward: none
  #       QueryString: false
  #     # allow-all | redirect-to-https | https-only
  #     ViewerProtocolPolicy: redirect-to-https
  #     PathPattern: /index.html

# dns_records:
#   - mycdn.${DnsDomain}

# logs:
#   bucket: mybucket.com
#   prefix: mysite
